version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/rockset/aws-sm-env
    steps:
      - checkout
      - run: go test -v
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/rockset/aws-sm-env
    steps:
      - checkout
      - run: go build -o ./artifacts/aws-sm-env
      - persist_to_workspace:
          root: ./artifacts
          paths:
            - aws-sm-env
  publish:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run echo "uploading release with tag ${CIRCLE_TAG}"
      - run ls -l ./artifacts/aws-sm-env
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u -delete ${CIRCLE_TAG} ./artifacts/aws-sm-env
workflows:
  version: 2
  build_and_publish:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v\d+\.\d+\.\d+$/
