version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/rockset/aws-sm-env
    steps:
      - checkout
      - run: go test -v
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/rockset/aws-sm-env
    steps:
      - checkout
      - run: go build -ldflags "-linkmode external -extldflags -static" -o ./artifacts/aws-sm-env
      - persist_to_workspace:
          root: ./artifacts
          paths:
            - aws-sm-env
  publish:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/aws-sm-env

workflows:
  version: 2
  build_and_publish:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
